### ISSUE TITLE
Names.parseName slow due to regex pattern compilation

### ISSUE THREAD

**Issue by DanielThomas** [Netflix/frigga#21]
`extractLabeledVariable` is called 8 times during `Names.<init>` and those patterns are being compiled on the fly. These could at least be short-circuited if `labeledVariables` is empty, and ideally kept precompiled as static members in a map, on an enum, whatever.

**Comment by DanielThomas** [comment]
I've worked around this for our use case by holding onto the parsed names, but seems like a nice improvement.

**Comment by brharrington** [comment]
FWIW with the common IPC project we needed to parse ASG names and ended up just using different logic without regex, summary of JMH benchmarks:

https://github.com/Netflix/spectator/blob/master/spectator-ext-ipc/src/jmh/java/com/netflix/spectator/ipc/ServerGroupParsing.java#L26

Alternative parser:

https://github.com/Netflix/spectator/blob/master/spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/ServerGroup.java

That said if there are some simple improvements to frigga, it seems like that could benefit many teams.

**Comment by DanielThomas** [comment]
Ah, that alternative will work better for us - we're only ever doing this for server groups.
